POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "name": "Sara",
    "email": "sara@gmail.com",
    "password": "ss",
    "address": {
        "city": "San Francisco",
        "country": "Sweden",
        "line1": "123 Main St",
        "postal_code": "94105"
    }
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "ss@gmail.com",
    "password": "ss"
}

###
POST http://localhost:3001/api/auth/logout

###
GET http://localhost:3001/api/auth/authorize