POST http://localhost:3001/api/stripe/create-checkout-session 
Content-Type: application/json


  {"customerId": "cus_Q8SvGZA6KeL3Hg",
        [

          {
            "product": "price_1OjJm3KDYG89Sk1MV6TKHCWy",
            "quantity": 3
          },
          {
            "product": "price_1OjJkTKDYG89Sk1MeWycVhcr",
            "quantity": 1
        }]
  }


###
POST http://localhost:3001/api/stripe/verify-session    
Content-Type: application/json

{
    "sessionId": "cs_test_b1VY0wOiE5eodr4iuODQah94IYRYtpJeW9kkSyPYylX3nZuhftUV70WOeE"
}

###
GET  http://localhost:3001/api/stripe/products
